# site settings
title: JP
subtitle: Software Developer
copyright: Julius Parishy
email: hello@juliusparishy.com
description1: "Philadelphia, PA"
description2: "I build cool stuff"
description3: "Apps, websites, REST APIs"
baseurl: "" # the subpath of your site, e.g. /blog
url: https://juliusparishy.com/
author: Julius Parishy
street_address: WeWork c/o Julius Parishy<br>1010 N. Hancock St
city: Philadelphia
state: PA
zip_code: 19123

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
github_url: https://github.com/jparishy
instagram_url: https://instagram.com/jparishy
twitter_url: https://twitter.com/jparishy

# build settings
markdown: kramdown

sass:
  style: compressed
