# site settings
title: JP
tab_title: Julius Parishy | Philadelphia Software Developer
subtitle: Software Developer
copyright: Julius Parishy
email: hello@juliusparishy.com
description1: "Philadelphia, PA"
description2: "I build cool stuff"
description3: "Apps, websites, REST APIs"
baseurl: "" # the subpath of your site, e.g. /blog
url: https://juliusparishy.com
author: Julius Parishy
street_address: Julius Parishy c/o WeWork<br>1010 N. Hancock St
city: Philadelphia
state: PA
zip_code: 19123
permalink: /:title

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings
github_url: https://github.com/jparishy
instagram_url: https://instagram.com/jparishy
twitter_url: https://twitter.com/jparishy

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-analytics

jekyll_analytics:
  GoogleAnalytics:
    id: UA-142500700-1
    anonymizeIp: false